salesforce/storm-dynamic-spout

src/test/java/com/salesforce/storm/spout/dynamic/DynamicSpoutTest.java, src/test/java/com/salesforce/storm/spout/dynamic/kafka/ConsumerTest.java, src/test/java/com/salesforce/storm/spout/dynamic/kafka/KafkaTestServer.java, src/test/java/com/salesforce/storm/spout/dynamic/kafka/KafkaTestServerTest.java, src/test/java/com/salesforce/storm/spout/dynamic/persistence/ZookeeperPersistenceAdapterTest.java, src/test/java/com/salesforce/storm/spout/dynamic/utils/KafkaTestServer.java, src/test/java/com/salesforce/storm/spout/dynamic/utils/KafkaTestServerTest.java, src/test/java/com/salesforce/storm/spout/dynamic/utils/KafkaTestUtils.java, src/test/java/com/salesforce/storm/spout/dynamic/utils/SharedKafkaTestResource.java, src/test/java/com/salesforce/storm/spout/dynamic/utils/SharedZookeeperTestResource.java
General clean up of Kafka Test Server class, removed some dead methods, added some utility methods to get the Kafka and Zookeeper connection strings.
Also refactored BeforeClass and AfterClass usages in tests around standing up internal kafka/zookeeper servers.  This logic got moved into a re-usable ClassRule resource to remove code duplication and standardize it.
=> Cleanup kafka test server class, refactor @BeforeClass and @AfterClass 

src/main/java/com/salesforce/storm/spout/dynamic/DynamicSpout.java, src/main/java/com/salesforce/storm/spout/dynamic/SpoutCoordinator.java, src/main/java/com/salesforce/storm/spout/sideline/handler/SidelineSpoutHandler.java, src/test/java/com/salesforce/storm/spout/dynamic/DynamicSpoutTest.java
@stanlemon Prior to splitting Sideline stuff out from DynamicSpout, we used a latch to synchronize all of the virtual spouts to start at the same time in the SpoutCoordinator.open() call on startup.
After the refactor, SpoutCoordinator.open() gets called prior to SidelineSpoutHandler.onSpoutOpen() (where virtual spouts get added) so we no longer have a guarantee around the virtual spouts starting at the same time. Once SidelineSpoutHandler starts adding VirtualSpouts they start immediately and begin consuming.  
(Relevant code in DynamicSpout.open(): https://github.com/salesforce/storm-dynamic-spout/blob/master/src/main/java/com/salesforce/storm/spout/dynamic/DynamicSpout.java#L165-L186 )
We had a race condition that showed up in …
=> Handle startup race condition in SidelineSpout Handler

src/test/resources/log4j2.xml
@stanlemon We talked about this a little bit before.
This change shouldn't alter what gets logged to the console currently.  But it adds a new log file under target/logs/test.log  This log file gets all INFO level logs, excluding a few things I thought were non-relevant.
In intellJ you can adjust your default JUnit configuration to tail this log automatically.
=> Revamp Log4j2 configuration into something sane

CHANGELOG.md, src/main/java/com/salesforce/storm/spout/dynamic/DynamicSpout.java, src/main/java/com/salesforce/storm/spout/dynamic/SpoutCoordinator.java, src/main/java/com/salesforce/storm/spout/dynamic/VirtualSpout.java, src/main/java/com/salesforce/storm/spout/dynamic/coordinator/SpoutMonitor.java, src/main/java/com/salesforce/storm/spout/dynamic/coordinator/SpoutMonitorFactory.java, src/main/java/com/salesforce/storm/spout/dynamic/coordinator/SpoutRunner.java, src/test/java/com/salesforce/storm/spout/dynamic/DynamicSpoutTest.java, src/test/java/com/salesforce/storm/spout/dynamic/SpoutCoordinatorTest.java, src/test/java/com/salesforce/storm/spout/dynamic/coordinator/SpoutMonitorTest.java, src/test/java/com/salesforce/storm/spout/dynamic/mocks/output/MockSpoutOutputCollector.java
First pass on #23 
This adds the ability for errors within Spout Coordinator / Spout Monitor to be bubbled up to storm.  We may want to continue this pattern and push access up into Virtual Spouts and/or Consumers?
=> Add ability for VirtualSpouts to report errors back to Storm

CHANGELOG.md, src/main/java/com/salesforce/storm/spout/dynamic/DynamicSpout.java, src/main/java/com/salesforce/storm/spout/dynamic/Tools.java, src/main/java/com/salesforce/storm/spout/dynamic/config/SpoutConfig.java, src/main/java/com/salesforce/storm/spout/dynamic/kafka/KafkaConsumerConfig.java, src/test/java/com/salesforce/storm/spout/dynamic/DynamicSpoutTest.java, src/test/java/com/salesforce/storm/spout/dynamic/ToolsTest.java, src/test/java/com/salesforce/storm/spout/dynamic/persistence/ZookeeperPersistenceAdapterTest.java, src/test/java/com/salesforce/storm/spout/dynamic/persistence/zookeeper/CuratorHelperTest.java, src/test/java/com/salesforce/storm/spout/sideline/persistence/ZookeeperPersistenceAdapterTest.java
fix for #33 
Values are now split on ',' using Gauva's split library, trimmed, and filtered for empty values.
=> [ISSUE-33] - trim output field values after splitting

CHANGELOG.md, src/main/java/com/salesforce/storm/spout/dynamic/kafka/Consumer.java
This PR slightly tweaks your metric collection loops in the following way:
- It condenses the two loops into a single loop, 
- Renames some of the variables to be more explicit
- Re-uses the result of getCurrentState() instead of calling it once per loop iteration
- Adds "currentOffset" metric
- Renames the metric keyspace "topic.[topic].partition.[partition].[metricName]" so its easier to browse related metrics in something like grafana/graphite.
- Updates changelog <-- May want to review and make any other changes here that I missed.
=> Slightly tweak how the metrics are calculated, condense into a single loop

CHANGELOG.md, README.md, src/main/java/com/salesforce/storm/spout/dynamic/DelegateSpout.java, src/main/java/com/salesforce/storm/spout/dynamic/VirtualSpout.java, src/main/java/com/salesforce/storm/spout/dynamic/consumer/Consumer.java, src/main/java/com/salesforce/storm/spout/dynamic/coordinator/SpoutPartitionProgressMonitor.java, src/main/java/com/salesforce/storm/spout/dynamic/kafka/Consumer.java, src/test/java/com/salesforce/storm/spout/dynamic/VirtualSpoutTest.java, src/test/java/com/salesforce/storm/spout/dynamic/consumer/MockConsumer.java, src/test/java/com/salesforce/storm/spout/dynamic/kafka/ConsumerTest.java, src/test/java/com/salesforce/storm/spout/dynamic/mocks/MockDelegateSpout.java
The getMaxLag() method has always felt awkward and it's another one of those situations where we are leaking our concerns across layers. I've wanted to switch this maxLag to be the endOffset and in other Consumer implementations we have a need for the ability to report metrics.  So this PR introduces the MetricsRecorder into the Consumer interface and drops the getMaxLag() metric in favor of a consumer specific one for the starting offset.
=> Drop VirtualSpout.getMaxLag() and pass the MetricsRecorder to Consumer

CHANGELOG.md, README.md, src/main/java/com/salesforce/storm/spout/dynamic/DynamicSpout.java, src/main/java/com/salesforce/storm/spout/dynamic/VirtualSpout.java, src/main/java/com/salesforce/storm/spout/dynamic/kafka/deserializer/Utf8StringDeserializer.java, src/main/java/com/salesforce/storm/spout/sideline/config/SidelineConfig.java, src/main/java/com/salesforce/storm/spout/sideline/handler/SidelineSpoutHandler.java, src/test/java/com/salesforce/storm/spout/dynamic/DynamicSpoutTest.java, src/test/java/com/salesforce/storm/spout/dynamic/buffer/RoundRobinBufferTest.java, src/test/java/com/salesforce/storm/spout/dynamic/filter/SerializerTest.java, src/test/java/com/salesforce/storm/spout/sideline/handler/SidelineSpoutHandlerTest.java, src/test/resources/log4j2.xml
VirtualSpouts can die. They shouldn't, but they do. FilterChains can get out of whack. They shouldn't, but they do. The SidelineSpoutHandler needs to periodically check its state and reload things to get them in the correct state.  This should be as simple as calling `loadSidelines()` periodically, but we need to add test coverage that jacking with the state of the spouts running and the various filter chains resumes correctly with subsequent calls. Then when all is said and done we can call loadSildelines() on an interval and we should be good to go.
=> SidelineSpoutHandler should periodically check its state and recover

pom.xml, src/main/java/com/salesforce/storm/spout/dynamic/filter/StaticMessageFilter.java, src/main/java/com/salesforce/storm/spout/dynamic/persistence/ZookeeperPersistenceAdapter.java, src/main/java/com/salesforce/storm/spout/dynamic/persistence/zookeeper/CuratorHelper.java, src/main/java/com/salesforce/storm/spout/sideline/persistence/ZookeeperPersistenceAdapter.java, src/main/java/com/salesforce/storm/spout/sideline/trigger/example/Config.java, src/main/java/com/salesforce/storm/spout/sideline/trigger/example/FilterChainStepBuilder.java, src/main/java/com/salesforce/storm/spout/sideline/trigger/example/TriggerEvent.java, src/main/java/com/salesforce/storm/spout/sideline/trigger/example/ZookeeperWatchTrigger.java, src/test/java/com/salesforce/storm/spout/dynamic/consumer/MockConsumer.java, src/test/java/com/salesforce/storm/spout/dynamic/persistence/zookeeper/CuratorHelperTest.java, src/test/java/com/salesforce/storm/spout/sideline/persistence/ZookeeperPersistenceAdapterTest.java, src/test/java/com/salesforce/storm/spout/sideline/trigger/example/ZookeeperWatchTriggerTest.java
=> Add a reference implementation of a SidelineTrigger using Zookeeper watches

src/main/java/com/salesforce/storm/spout/dynamic/coordinator/SpoutCoordinator.java, src/main/java/com/salesforce/storm/spout/dynamic/persistence/ZookeeperPersistenceAdapter.java, src/main/java/com/salesforce/storm/spout/dynamic/persistence/zookeeper/CuratorFactory.java, src/main/java/com/salesforce/storm/spout/sideline/handler/SidelineSpoutHandler.java, src/main/java/com/salesforce/storm/spout/sideline/handler/SidelineVirtualSpoutHandler.java, src/main/java/com/salesforce/storm/spout/sideline/persistence/ZookeeperPersistenceAdapter.java, src/main/java/com/salesforce/storm/spout/sideline/trigger/example/ZookeeperWatchTrigger.java, src/test/java/com/salesforce/storm/spout/dynamic/DynamicSpoutTest.java, src/test/java/com/salesforce/storm/spout/dynamic/persistence/ZookeeperPersistenceAdapterTest.java, src/test/java/com/salesforce/storm/spout/dynamic/persistence/zookeeper/CuratorHelperTest.java, src/test/java/com/salesforce/storm/spout/sideline/handler/SidelineVirtualSpoutHandlerTest.java, src/test/java/com/salesforce/storm/spout/sideline/persistence/ZookeeperPersistenceAdapterTest.java, src/test/java/com/salesforce/storm/spout/sideline/trigger/example/ZookeeperWatchTriggerTest.java
This PR deals with mysterious orphaned Curator threads within tests.
- Add close() definition to SidelineVirtualSpoutHandler implementation that closes Curator.
- Remove un-used SpoutHandler instance in test.
- Add context parameter to CuratorFactory.
=> Add missing close implementation, better naming of threads

src/main/java/com/salesforce/storm/spout/dynamic/DelegateSpoutFactory.java, src/main/java/com/salesforce/storm/spout/dynamic/DynamicSpout.java, src/main/java/com/salesforce/storm/spout/dynamic/FactoryManager.java, src/main/java/com/salesforce/storm/spout/dynamic/VirtualSpoutFactory.java, src/main/java/com/salesforce/storm/spout/dynamic/config/SpoutConfig.java, src/main/java/com/salesforce/storm/spout/dynamic/handler/SpoutHandler.java, src/main/java/com/salesforce/storm/spout/sideline/handler/SidelineSpoutHandler.java, src/test/java/com/salesforce/storm/spout/dynamic/VirtualSpoutFactoryTest.java, src/test/java/com/salesforce/storm/spout/sideline/handler/SidelineSpoutHandlerTest.java
IMO this is related to #70 as you can tell by some of the naming weirdness.
`FactoryManager` doesn't have any facilities for passing arguments to a constructor, which is why it was not used to create the `VirtualSpoutFactory`.
I have mixed feelings about the generics in `DelegateSpoutFactory`, in the end if this is not done we wind up casting, so I think this is a better option honestly.
Note that right now the `FilterChain` is part of `VirtualSpout` and not of `DelegateSpout`, I think this is worth calling out because it is the primary reason why someone would want to directly type against `VirtualSpout` today. Perhaps we should reconsider this, I'm open to this - we just need to make a decision that the `FilterChain` is a first class citizen in the interface and that we expect …
=> Use a factory to create VirtualSpout instances

CHANGELOG.md, src/main/java/com/salesforce/storm/spout/dynamic/DynamicSpout.java, src/test/java/com/salesforce/storm/spout/dynamic/DynamicSpoutTest.java, src/test/java/com/salesforce/storm/spout/dynamic/KafkaConsumerSpoutTest.java, src/test/java/com/salesforce/storm/spout/dynamic/mocks/MockConsumer.java, src/test/java/com/salesforce/storm/spout/dynamic/mocks/MockDelegateSpout.java, src/test/java/com/salesforce/storm/spout/dynamic/mocks/MockSpoutHandler.java, src/test/java/com/salesforce/storm/spout/sideline/SidelineSpoutTest.java, src/test/java/com/salesforce/storm/spout/sideline/handler/SidelineSpoutHandlerTest.java, src/test/java/com/salesforce/storm/spout/sideline/handler/SidelineVirtualSpoutHandlerTest.java, src/test/java/com/salesforce/storm/spout/sideline/trigger/example/ZookeeperWatchTriggerTest.java
Start to breakup the integration test DynamicSpoutTest into:
- DynamicSpoutTest - Covering DynamicSpout using a stand-in MockConsumer (and no sidelining logic)
- SidelineSpoutTest - Covering just the Sidelining functionality, makes use of KafkaConsumer to help validate various scenarios.  
- KafkaConsumerTest - Integration test covering the KafkaConsumer within DynamicSpout, covers no sidelining logic.
This moves us towards being able to do #19
=> Breaking up Integration tests

src/main/java/com/salesforce/storm/spout/dynamic/DelegateSpout.java, src/main/java/com/salesforce/storm/spout/dynamic/VirtualSpout.java, src/test/java/com/salesforce/storm/spout/dynamic/VirtualSpoutTest.java, src/test/java/com/salesforce/storm/spout/dynamic/mocks/MockDelegateSpout.java
This is being added so that you can create an open ended spout, meaning one where you don't yet know the ending state but might need to set it down the road.  This is the first step in moving our sideline implementation to support what's been called 'throttling'.
=> Allow ending state to be set after a VirtualSpout has been created

src/main/java/com/salesforce/storm/spout/sideline/handler/SidelineSpoutHandler.java, src/main/java/com/salesforce/storm/spout/sideline/handler/SidelineVirtualSpoutHandler.java, src/main/java/com/salesforce/storm/spout/sideline/persistence/InMemoryPersistenceAdapter.java, src/main/java/com/salesforce/storm/spout/sideline/persistence/PersistenceAdapter.java, src/main/java/com/salesforce/storm/spout/sideline/persistence/ZookeeperPersistenceAdapter.java, src/test/java/com/salesforce/storm/spout/sideline/handler/SidelineSpoutHandlerTest.java, src/test/java/com/salesforce/storm/spout/sideline/handler/SidelineVirtualSpoutHandlerTest.java, src/test/java/com/salesforce/storm/spout/sideline/persistence/ZookeeperPersistenceAdapterTest.java
The goal here is to not have to call out to the kafka config for the topic by relying on `ConsumerPartition` directly. Long term we could actually use `ConsumerState` wholesale here and let the specific persistence adapter loop over the partitions - if they need to.
Addresses comment #46
=> Switch to using ConsumerPartition for sideline persistence

CHANGELOG.md, src/main/java/com/salesforce/storm/spout/dynamic/consumer/Consumer.java, src/main/java/com/salesforce/storm/spout/dynamic/kafka/Consumer.java, src/test/java/com/salesforce/storm/spout/dynamic/VirtualSpoutTest.java, src/test/java/com/salesforce/storm/spout/dynamic/mocks/MockConsumer.java
We never reference this public interface method, so lets remove it from the interface.
=> Remove un-used method from Consumer interface

CHANGELOG.md, src/main/java/com/salesforce/storm/spout/dynamic/retry/DefaultRetryManager.java, src/test/java/com/salesforce/storm/spout/dynamic/retry/DefaultRetryManagerTest.java
Previously the implementation would return messageIds that were closest to the current timestamp instead of the messageIds which failed earlier.  This means if there was a high rate of sustained failures, the earlier failed messageIds may never have gotten replayed.
=> Fix ordering bug in DefaultRetryManager.

src/main/java/com/salesforce/storm/spout/sideline/handler/SidelineSpoutHandler.java
Add checks and skip in loop if this should happen. This most likely occurs when there's bad serialization occurring on sideline requests.
=> Check for nulls and log accordingly

src/main/java/com/salesforce/storm/spout/dynamic/consumer/PartitionDistributor.java, src/test/java/com/salesforce/storm/spout/dynamic/consumer/PartitionDistributorTest.java
The current partition distribution implementation attempts to distribute the maximum number of partitions to each consumer, such that when the number of consumer instances is not a multiplier of the partition count the ending instances are left with no partitions.  For example consider 4 partitions across 3 instances, the current implementation will give instances 1 & 2 two partitions each and leave instance 3 with no partitions.
The new implementation attempts to make sure every instance has at least one partition, unless there are more instances than partitions, and will distribute up to the max partition per instance number to as many instances as it can.  The trick here is that we still want the partitions ordered such that with 4 partitions across 3 instances, instance 1 should have …
=> More fair partition distribution with weird number of partitions

src/main/java/com/salesforce/storm/spout/dynamic/VirtualSpout.java
**Summary**
When VirtualSpout decides that a fail()'d message should NOT be retried, it notifies the retry manager to 'ack' it, and notifies the consumer to 'ack' it.  Unfortunately what it did NOT do was remove it from the `trackedMessages` map.  This map contains a mapping of all messages in flight, mapping their messageId => message.
Because we were not removing from this map, if a VirtualSpout had a large number of failed messages that exceeded the fail threshold, those map entries would linger around and never be cleaned up, until the vspout was closed.  This results in a memory leak.
**Solution**
I think the proper solution is to just call ack() on the messageId in this scenario.  This should mark the message as being ack'd in all the required ways.
=> Fix failed message leak.  the message was never removed from trackedMap in certain scenarios

CHANGELOG.md, README.md, src/main/java/com/salesforce/storm/spout/dynamic/DynamicSpout.java, src/main/java/com/salesforce/storm/spout/dynamic/Message.java, src/main/java/com/salesforce/storm/spout/dynamic/VirtualSpout.java, src/main/java/com/salesforce/storm/spout/dynamic/config/SpoutConfig.java, src/test/java/com/salesforce/storm/spout/dynamic/DynamicSpoutTest.java, src/test/java/com/salesforce/storm/spout/dynamic/MessageTest.java, src/test/java/com/salesforce/storm/spout/dynamic/VirtualSpoutTest.java
**Use Case**
We'd like the ability to handle tuples that are considered "permanently failed".  We're defining "permanently failed" meaning that the topology attempted to process the tuple at least once and the `RetryManager` implementation has determined that the tuple should never be retried.  When this occurs, the tuple will be emitted un-anchored out a "failed" stream.  Bolts within the topology can subscribe to this "failed" stream and do its own error handling.
It should be noted (again) that tuples emitted on the "failed" stream are un-anchored and should be considered unreliable.  IE. The spout will not track it or be notified of failed or acked tuples emitted down this "failed" stream.
**Notes**
One idea was to move the RetryFailedMessageManager out of the VirtualSpouts and only …
=> First pass at a permanently failed output stream from the spout.

CHANGELOG.md, pom.xml, src/main/java/com/salesforce/storm/spout/dynamic/persistence/zookeeper/CuratorHelper.java, src/test/java/com/salesforce/storm/spout/dynamic/persistence/zookeeper/CuratorHelperTest.java
Handle race condition between checking if a node exists, and removing the node.
Backporting bugfix to 0.9.x release: #92 
Cuts bugfix version 0.9.2
=> Catch and swallow no-node exceptions (#93)

src/main/java/com/salesforce/storm/spout/dynamic/DelegateSpout.java, src/main/java/com/salesforce/storm/spout/dynamic/VirtualSpout.java, src/main/java/com/salesforce/storm/spout/dynamic/coordinator/SpoutRunner.java, src/test/java/com/salesforce/storm/spout/dynamic/VirtualSpoutTest.java, src/test/java/com/salesforce/storm/spout/dynamic/coordinator/SpoutCoordinatorTest.java, src/test/java/com/salesforce/storm/spout/dynamic/coordinator/SpoutRunnerTest.java, src/test/java/com/salesforce/storm/spout/dynamic/mocks/MockDelegateSpout.java
I would contend that the tiers of SpoutRunner -> VirtualSpout around isStopRequested() are a bit of a smell. I think what we were doing in VirtualSpout was actually the isCompleted() method, but we hadn't exposed it.  Basically, we wanted a way for the VirtualSpout to indicate it was done processing and that it could be automatically removed from the coordinator.
Additionally, I think the addition of removeVirtualSpout() elsewhere handles the scenario of "kill this VirtualSpout early" and is a much cleaner interface for doing so.
=> Dropping requestStop() from the DelegateSpout

src/main/java/com/salesforce/storm/spout/dynamic/DynamicSpout.java, src/main/java/com/salesforce/storm/spout/dynamic/FactoryManager.java, src/main/java/com/salesforce/storm/spout/dynamic/coordinator/SpoutCoordinator.java, src/main/java/com/salesforce/storm/spout/sideline/handler/SidelineSpoutHandler.java, src/main/java/com/salesforce/storm/spout/sideline/persistence/ZookeeperPersistenceAdapter.java, src/main/java/com/salesforce/storm/spout/sideline/trigger/example/ZookeeperWatchTrigger.java, src/test/java/com/salesforce/storm/spout/dynamic/VirtualSpoutTest.java, src/test/java/com/salesforce/storm/spout/dynamic/coordinator/SpoutCoordinatorTest.java, src/test/java/com/salesforce/storm/spout/dynamic/filter/FilterChainTest.java, src/test/java/com/salesforce/storm/spout/dynamic/kafka/ConsumerTest.java
Continue to work towards removing Sideline dependency out of DynamicSpout core package space.
Removes dependencies within tests to Sideline classes, but the tests themselves don't actually depend on any sideline logic.  So swapped them out with their Default implementations.
=> Remove references to sideline from DynamicSpout tests

src/main/java/com/salesforce/storm/spout/dynamic/DelegateSpout.java, src/main/java/com/salesforce/storm/spout/dynamic/DynamicSpout.java, src/main/java/com/salesforce/storm/spout/dynamic/VirtualSpout.java, src/main/java/com/salesforce/storm/spout/dynamic/coordinator/SpoutCoordinator.java, src/main/java/com/salesforce/storm/spout/sideline/handler/SidelineController.java, src/main/java/com/salesforce/storm/spout/sideline/handler/SidelineSpoutHandler.java, src/main/java/com/salesforce/storm/spout/sideline/metrics/SidelineMetrics.java, src/main/java/com/salesforce/storm/spout/sideline/trigger/SidelineType.java, src/main/java/com/salesforce/storm/spout/sideline/trigger/example/TriggerEvent.java, src/main/java/com/salesforce/storm/spout/sideline/trigger/example/ZookeeperWatchTrigger.java, src/test/java/com/salesforce/storm/spout/dynamic/mocks/MockDelegateSpout.java, src/test/java/com/salesforce/storm/spout/sideline/SidelineSpoutTest.java, src/test/java/com/salesforce/storm/spout/sideline/handler/SidelineSpoutHandlerTest.java, src/test/java/com/salesforce/storm/spout/sideline/handler/SidelineVirtualSpoutHandlerTest.java, src/test/java/com/salesforce/storm/spout/sideline/persistence/ZookeeperPersistenceAdapterTest.java, src/test/java/com/salesforce/storm/spout/sideline/trigger/StaticTrigger.java, src/test/java/com/salesforce/storm/spout/sideline/trigger/example/ZookeeperWatchTriggerTest.java, src/test/resources/log4j2.xml
This PR adds a new state to the sideline sequence which we are calling **resume**. 
Today sidelines are binary, they can be started or stopped.  Starting a sideline means that a starting offset is captured for a future virtual spout and a filter is applied to the firehose virtual spout.  This is typically done around the concept of a 'tenant', for example you might want to sideline account _Foobar_ for a period of time.  Stopping a sideline means that an ending offset is captured for a virtual spout that will be now created using the starting offset saved during the start of the sideline. That new virtual spout is immediately added to the coordinator with a filter that only emits the tenant in question and the filter is removed altogether from the firehose.
The consequences of the binary …
=> Add support for resume state in sidelining

CHANGELOG.md, src/main/java/com/salesforce/storm/spout/sideline/handler/SidelineSpoutHandler.java, src/test/java/com/salesforce/storm/spout/sideline/handler/SidelineSpoutHandlerTest.java
When redeploying a topology with an existing sideline in the resume state I noticed the sideline failed to load because of the exception thrown at https://github.com/salesforce/storm-dynamic-spout/blob/2dc9dbd394b81ed7516068b32c9b58589d3729a7/src/main/java/com/salesforce/storm/spout/dynamic/VirtualSpout.java#L347-L353
This is because there is no ending state set in the resume, but we instantiate the builder regardless and never populate it. To avoid this exception I added a check to make sure that the ending state is empty, and if it is to pass null on instead.
=> Do not pass empty ending state when loading sidelines

CHANGELOG.md, src/main/java/com/salesforce/storm/spout/dynamic/buffer/RatioMessageBuffer.java, src/test/java/com/salesforce/storm/spout/dynamic/buffer/RatioMessageBufferTest.java
Bugfix for #100 
This code would previously NPE on Spout deploy because at deploy time there are no VirtualSpouts to be iterated over.
=> [ISSUE-100] - Fix NPE in RatioMessageBuffer on spout deploy

CHANGELOG.md, src/main/java/com/salesforce/storm/spout/dynamic/retry/DefaultRetryManager.java, src/test/java/com/salesforce/storm/spout/dynamic/retry/DefaultRetryManagerTest.java
While debugging retries, I noticed that the current retry behavior follows linear growth (2, 4, 6, 8 seconds). However, the comments on the DefaultRetryManager class and retry variables imply expontential growth (2, 4, 8, 16, etc.).
This fixes the retry code to grow exponentially as expected.
=> Change the default retry delay to have exponential growth

src/main/java/com/salesforce/storm/spout/sideline/recipes/trigger/FilterChainStepBuilder.java, src/main/java/com/salesforce/storm/spout/sideline/recipes/trigger/TriggerEvent.java, src/main/java/com/salesforce/storm/spout/sideline/recipes/trigger/zookeeper/Config.java, src/main/java/com/salesforce/storm/spout/sideline/recipes/trigger/zookeeper/ZookeeperWatchTrigger.java, src/test/java/com/salesforce/storm/spout/sideline/recipes/trigger/zookeeper/ZookeeperWatchTriggerTest.java
These classes are intended for actual use. The nomenclature of 'recipes' seems to be more common for this sort of thing. Furthermore, I'm concerned people might think 'examples' are not intended for actual use. Thus I'm renaming this package, and I am also moving the common classes one level up so that we can do future implementation with them (eg. redis).
=> Rename examples to recipes

src/main/java/com/salesforce/storm/spout/dynamic/metrics/KeyBuilder.java, src/main/java/com/salesforce/storm/spout/dynamic/metrics/LogRecorder.java, src/main/java/com/salesforce/storm/spout/dynamic/metrics/MetricsRecorder.java, src/main/java/com/salesforce/storm/spout/dynamic/metrics/StormRecorder.java, src/main/java/com/salesforce/storm/spout/dynamic/metrics/TimerManager.java, src/test/java/com/salesforce/storm/spout/dynamic/metrics/KeyBuilderTest.java, src/test/java/com/salesforce/storm/spout/dynamic/metrics/TimerManagerTest.java
First part in my work on #117, this takes several bits of code that are reused between `StormRecorder` and `LogRecorder` and breaks them out so that they can be used in a forthcoming `DropwizardRecorder` implementation.
=> Metrics Refactoring

src/main/java/com/salesforce/storm/spout/dynamic/JSON.java, src/main/java/com/salesforce/storm/spout/dynamic/Tools.java, src/main/java/com/salesforce/storm/spout/dynamic/persistence/zookeeper/CuratorHelper.java, src/main/java/com/salesforce/storm/spout/sideline/persistence/ZookeeperPersistenceAdapter.java, src/main/java/com/salesforce/storm/spout/sideline/recipes/trigger/zookeeper/Config.java, src/main/java/com/salesforce/storm/spout/sideline/recipes/trigger/zookeeper/ZookeeperWatchTrigger.java, src/main/java/com/salesforce/storm/spout/sideline/trigger/SidelineType.java, src/test/java/com/salesforce/storm/spout/dynamic/JSONTest.java, src/test/java/com/salesforce/storm/spout/dynamic/persistence/zookeeper/CuratorHelperTest.java, src/test/java/com/salesforce/storm/spout/sideline/recipes/trigger/zookeeper/ZookeeperWatchTriggerTest.java, src/test/java/com/salesforce/storm/spout/sideline/trigger/SidelineTypeTest.java
Most of this is simple cleanup. There is one notable change though, in the original reference implementation for 0.10 the zookeeper watch supports multiple roots. I don't recall what the reason for this complexity was, probably accounting for the weird way we tried handling global sidelines in the implementation that preceded this. I am confident that there's a better/cleaner way of doing that. I am just not sure that additional complexity is worth it.
=> Zookeeper reference implementation cleanup

.travis.yml, src/main/java/com/salesforce/storm/spout/dynamic/VirtualSpout.java, src/main/java/com/salesforce/storm/spout/dynamic/kafka/Consumer.java, src/main/java/com/salesforce/storm/spout/sideline/config/SidelineConfig.java, src/main/java/com/salesforce/storm/spout/sideline/recipes/trigger/zookeeper/Config.java, src/main/java/com/salesforce/storm/spout/sideline/recipes/trigger/zookeeper/ZookeeperWatchTrigger.java, src/test/java/com/salesforce/storm/spout/dynamic/VirtualSpoutTest.java
The 'root' configuration only supports one root, this typo is a holdover from the old implementation where we supported a list of roots to watch.
=> Fix sideline zk configuration

src/main/java/com/salesforce/storm/spout/dynamic/Tools.java, src/main/java/com/salesforce/storm/spout/sideline/recipes/trigger/TriggerEventHelper.java, src/main/java/com/salesforce/storm/spout/sideline/recipes/trigger/zookeeper/ZookeeperWatchTrigger.java, src/test/java/com/salesforce/storm/spout/sideline/recipes/trigger/TriggerEventHelperTest.java
The goal here is to provide an implementation for generating the trigger events leveraged by the recipe. This can be used in a variety of places, such as command-line tooling or a thin api.
=> Implement helper for handling trigger events
